# Site settings
title: "WTF | PDQuin"
subtitle: "Write | Teach | Format | The arc of a working life"
email: himself@pdquin.com
description: "Sharing geeky designer how-tos, write/design trials and random notes"
baseurl: 
url: 
author:
 twitter: pdquin
 github: pdquin

# Build settings
markdown: kramdown
permalink: /:title.html
paginate: 5
paginate_path: "blog/page:num"
